config/routes.rb
Sampleapp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
    
  end
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  match '/register',    :to => 'users#new'
  match '/login',       :to => 'sessions#new'
  match '/logout',      :to => 'sessions#destroy'

  match '/contact',     :to => 'pages#contact'
  match '/about',       :to => 'pages#about'  
  match '/partners',    :to => 'pages#partners'
  
  root :to => 'pages#home'

end

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
 <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
 is a project to make a book and screencasts to teach web development
 with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
 is the sample application for the tutorial.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/home.html.erb
<% if logged_in? %>
	<table class="front" summary="For logged-in users">
		<tr>
			<td class="main">
				<h1 class="micropost">What's your status?</h1>
				<%= render 'shared/micropost_form' %>
				<%= render 'shared/feed' %>
			</td>
			<td class="sidebar round">
				<%= render 'shared/user_info' %>
				<%= render 'shared/stats' %>
			</td>
		</tr>
	</table>
<% else %>
	<h1>Company Micro Blog</h1>
	<p>
	  This is the home page for the Venator Ventures' micro-blogging application. 
		If you are a new parter with us, please visit our
		<%= link_to "Partners page", partners_path %> for more information.
		Otherwise, you can just log in from the top-right corner of this page.
	</p>
<% end %>

app/views/pages/partners.html.erb
<h1>Partners</h1>
<h3>Please login for access to project specific areas of the site.</h3>
<p>
	Logging in is required for other interactions with our site such as 
	commenting on the blog or providing feedback on our ideas. The login/logout 
	link is also found is also found at the top-right of most pages.
</p>
<%= link_to "Login", login_path, :class => "login_button round" %>
<p></p>
<h3>If you are not already registered you can do so below.</h3>
<p>
	Please be sure to tell
	us what project or initiative you are involved with in the comments section. 
	Once you have competed the registration, our site admin will grant you the 
	appropriate access privileges.<br>
</p>

<%= link_to "Register Now", register_path, :class => "register_button round" %>